# Generated by Django 6.0.3 on 2026-05-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': "O'qituvchi", 'verbose_name_plural': "O'qituvchilar"},
        ),
    ]
