# Generated by Django 6.0.5 on 2026-05-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Natija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('umumiy_savollar', models.IntegerField()),
                ('togrilari', models.IntegerField()),
                ('xatolari', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(max_length=200)),
                ('javob_a', models.CharField(max_length=100)),
                ('javob_b', models.CharField(max_length=100)),
                ('javob_c', models.CharField(max_length=100)),
                ('javob_d', models.CharField(max_length=100)),
                ('javob', models.CharField(choices=[('A', 'A variantı'), ('B', 'B variantı'), ('C', 'C variantı'), ('D', 'D variantı')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Test_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savollar.guruh')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savollar.kurs')),
            ],
        ),
    ]
