# Generated by Django 6.0.3 on 2026-05-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savollar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savollar.test_session'),
        ),
    ]
