# Generated by Django 6.0.3 on 2026-05-20 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savollar', '0002_alter_teacher_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guruh',
            options={'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
        migrations.AlterModelOptions(
            name='kurs',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='natija',
            options={'verbose_name': 'Natija', 'verbose_name_plural': 'Natijallar'},
        ),
        migrations.AlterModelOptions(
            name='savol',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': "O'qituvchi", 'verbose_name_plural': "O'qituvchilar"},
        ),
        migrations.AlterModelOptions(
            name='test_session',
            options={'verbose_name': 'Test Sessiya', 'verbose_name_plural': 'Test Sessiyalar'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='code',
        ),
        migrations.AddField(
            model_name='savol',
            name='kurs',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='savollar.kurs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='test_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='savollar.test_session'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='guruh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='savollar.guruh'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='savollar.kurs'),
        ),
    ]
