# Generated by Django 6.0.5 on 2026-05-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savollar', '0003_alter_guruh_options_alter_kurs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='test_session',
        ),
        migrations.AddField(
            model_name='natija',
            name='test_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='savollar.test_session'),
        ),
        migrations.AddField(
            model_name='test_session',
            name='guruh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='savollar.guruh'),
        ),
        migrations.AddField(
            model_name='test_session',
            name='kurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='savollar.kurs'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='guruh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='savollar.guruh'),
        ),
    ]
