# Generated by Django 6.0.5 on 2026-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savollar', '0005_code_alter_test_session_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_session',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Code',
        ),
    ]
