# Generated by Django 6.0.5 on 2026-05-21 15:40

import savollar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savollar', '0006_alter_test_session_code_delete_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_session',
            name='code',
            field=models.CharField(default=savollar.models.generate_code, max_length=4, unique=True),
        ),
    ]
