# Generated by Django 6.0.5 on 2026-05-29 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savollar', '0007_alter_test_session_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='natija',
            options={},
        ),
        migrations.RemoveField(
            model_name='natija',
            name='togrilari',
        ),
        migrations.RemoveField(
            model_name='natija',
            name='umumiy_savollar',
        ),
        migrations.RemoveField(
            model_name='natija',
            name='xatolari',
        ),
        migrations.AlterField(
            model_name='natija',
            name='test_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='savollar.test_session'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
